[tools]
chezmoi = "latest"
codex = "latest"
gh = "latest"
node = "26.8.2"
"pipx:basedpyright" = "latest"
"pipx:hermes-agent" = { version = "latest", extras = "all" }
pnpm = "latest"
python = "3.14"
uv = "latest"

[settings.upgrade]
auto_prune = false
